# Travis Configuration File
#
# For detailed information see https://docs.travis-ci.com/.

# Programming language
language: c++

# We require sudo to install additional packages
sudo: required

# Default Operating Systems
os:   linux
dist: trusty

matrix:
  include:
    - env: COMPILER=clang++-3.6 CUDA=8.0
      addons: &clang36
        packages:
          - clang-3.6
          - g++-5
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6

    - env: COMPILER=clang++-3.6 CUDA=9.1
      addons: *clang36

    - env: COMPILER=clang++-3.7 CUDA=8.0
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - g++-5
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7

# Installing additional packages
before_install:
  - source .travis/install_cuda.sh

script:
  - make
  - make test