# Travis Configuration File
#
# For detailed information see https://docs.travis-ci.com/.

# Programming language
language: c++

# We require sudo to install additional packages
sudo: required

# Operating Systems
os:
  - linux

# Compilers
compiler:
  - gcc
  - clang

# Environment variables
env:
  - CUDA=8.0

# Installing additional packages
before_install:
  - source .travis/install_cuda.sh

script:
  - make
  - make test