# Travis Configuration File
#
# For detailed information see https://docs.travis-ci.com/.

# Programming language
language: c++

# We require sudo to install additional packages
sudo: required

# Default Operating Systems
os:   linux
dist: trusty

matrix:
  include:
    # ----------------------------------------------------------------
    #  GCC
    # ----------------------------------------------------------------
    - compiler: gcc
      env:
        - CUDA=8.0

    - compiler: gcc
      addons: &gcc49
        packages:
          - g++-4.9
        sources:
          - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
        - CUDA=8.0

    - compiler: gcc
      addons: &gcc5
        packages:
          - g++-5
        sources:
          - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - CUDA=8.0

    - compiler: gcc
      addons: &gcc6
        packages:
          - g++-6
        sources:
          - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - CUDA=8.0

    - compiler: gcc
      addons: &gcc7
        packages:
          - g++-7
        sources:
          - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CUDA=8.0

    # ----------------------------------------------------------------
    #  Clang
    # ----------------------------------------------------------------
    - compiler: clang
      addons: &clang36
        packages:
          - clang-3.6
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
        - CUDA=8.0

    - compiler: clang
      addons: *clang36
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
        - CUDA=9.1

    - compiler: clang
      addons: &clang37
        apt:
          packages:
            - clang-3.7
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
        - CUDA=8.0

# Installing additional packages
before_install:
  - eval "${MATRIX_EVAL}"
  - source .travis/install_cuda.sh

script:
  - make
  - make test